import { useState } from 'react'
import { ArrowRight, ArrowUpRight, CalendarDays, Check, CircleAlert, FileDown, History, LockKeyhole, Plus } from 'lucide-react'
import { demoReports, serviceProgress } from '../../data/demo'
import type { AppPage, ReportStatus } from '../../types/spm'
import './DashboardPage.css'

interface DashboardPageProps { onNavigate: (page: AppPage) => void }
const statusClass: Record<ReportStatus, string> = { 'Belum diisi': 'status-empty', 'Sudah dicatat': 'status-saved', 'Periode terkunci': 'status-locked' }
const formattedDate = new Intl.DateTimeFormat('id-ID', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(new Date()).toLocaleUpperCase('id-ID')

function DashboardPage({ onNavigate }: DashboardPageProps) {
  const [period, setPeriod] = useState('September 2026')

  return (
    <div className="dashboard-page">
      <div className="page-heading"><div><span className="eyebrow">{formattedDate}</span><h1>Ringkasan SPM</h1><p>Pantau pengumpulan dan capaian Standar Pelayanan Minimal rumah sakit.</p></div><div className="heading-actions"><label className="period-select"><CalendarDays size={15} /><select aria-label="Pilih periode laporan" value={period} onChange={(event) => setPeriod(event.target.value)}><option>Oktober 2026</option><option>September 2026</option><option>Agustus 2026</option></select></label><button className="primary-button" type="button" onClick={() => onNavigate('entry')}><Plus size={16} /> Input laporan</button></div></div>
      <div className="data-notice"><CircleAlert size={16} /><span><strong>Data simulasi.</strong> Angka di halaman ini hanya contoh untuk pratinjau, bukan data resmi RSUD.</span></div>
      <section className="metric-grid" aria-label="Ringkasan periode">
        <article className="metric-card"><div className="metric-top"><span>Data sudah dicatat</span><span className="metric-icon green-icon"><FileDown size={16} /></span></div><strong className="metric-value">28 <small>/ 36</small></strong><div className="metric-foot"><span className="trend-positive"><ArrowUpRight size={13} /> 4 unit</span><span>dibanding bulan lalu</span></div></article>
        <article className="metric-card"><div className="metric-top"><span>Periode terkunci</span><span className="metric-icon amber-icon"><LockKeyhole size={16} /></span></div><strong className="metric-value">1</strong><div className="metric-foot"><span className="metric-subtle">September 2026</span></div></article>
        <article className="metric-card"><div className="metric-top"><span>Memenuhi standar</span><span className="metric-icon green-icon"><Check size={16} /></span></div><strong className="metric-value">84<small>%</small></strong><div className="metric-foot"><span className="trend-positive"><ArrowUpRight size={13} /> 3,2%</span><span>dibanding bulan lalu</span></div></article>
        <article className="metric-card"><div className="metric-top"><span>Belum diinput</span><span className="metric-icon coral-icon"><CircleAlert size={16} /></span></div><strong className="metric-value">8</strong><div className="metric-foot"><span className="metric-subtle">Tenggat 10 Oktober</span></div></article>
      </section>
      <div className="dashboard-columns">
        <section className="panel progress-panel"><div className="panel-heading"><div><h2>Progres pelaporan unit</h2><p>Indikator terkumpul untuk {period}</p></div><button className="text-button" type="button" onClick={() => onNavigate('reports')}>Semua unit <ArrowRight size={14} /></button></div><div className="progress-list">{serviceProgress.map((item) => { const percent = Math.round((item.done / item.total) * 100); return <div className="progress-row" key={item.name}><div className="progress-label"><span>{item.name}</span><strong>{item.done}<small>/{item.total}</small></strong></div><div className="progress-track"><span className={`progress-fill fill-${item.color}`} style={{ width: `${percent}%` }} /></div><span className="progress-percent">{percent}%</span></div> })}</div><div className="progress-footnote"><span className="legend-dot" /> Data masuk <span className="legend-dot legend-pale" /> Belum masuk</div></section>
        <section className="panel attention-panel"><div className="panel-heading"><div><h2>Perlu perhatian</h2><p>Data dan periode</p></div><span className="attention-total">3</span></div><div className="attention-item"><span className="attention-mark mark-coral"><CircleAlert size={15} /></span><div><strong>Radiologi belum mengisi</strong><small>8 indikator · tenggat 10 Oktober</small></div><button type="button" aria-label="Buka input laporan" onClick={() => onNavigate('entry')}><ArrowRight size={15} /></button></div><div className="attention-item"><span className="attention-mark mark-amber"><LockKeyhole size={15} /></span><div><strong>September sudah dikunci</strong><small>Data tersimpan sebagai baca-saja</small></div><button type="button" aria-label="Buka pengaturan periode" onClick={() => onNavigate('periods')}><ArrowRight size={15} /></button></div><div className="attention-item"><span className="attention-mark mark-blue"><History size={15} /></span><div><strong>Perubahan data tercatat</strong><small>Jejak pengguna dan nilai tersedia</small></div><button type="button" aria-label="Lihat jejak perubahan" onClick={() => onNavigate('audit')}><ArrowRight size={15} /></button></div></section>
      </div>
      <section className="panel recent-panel"><div className="panel-heading"><div><h2>Data terbaru</h2><p>Input capaian langsung dari unit pelayanan</p></div><button className="text-button" type="button" onClick={() => onNavigate('reports')}>Lihat rekap <ArrowRight size={14} /></button></div><div className="table-wrap"><table className="report-table"><thead><tr><th>UNIT / INSTALASI</th><th>PERIODE</th><th>KELENGKAPAN</th><th>KONDISI</th><th>TERAKHIR DIUBAH</th><th><span className="sr-only">Aksi</span></th></tr></thead><tbody>{demoReports.slice(0, 4).map((report) => <tr key={report.id}><td><strong>{report.unit}</strong><small>{report.id}</small></td><td>{report.period}</td><td><div className="table-progress"><span><i style={{ width: `${report.completion}%` }} /></span><small>{report.completion}%</small></div></td><td><span className={`status-badge ${statusClass[report.status]}`}>{report.status}</span></td><td className="updated-cell">{report.updatedAt}<small className="changed-by">{report.changedBy}</small></td><td><button className="row-action" type="button" aria-label={`Buka data ${report.unit}`} onClick={() => onNavigate(report.status === 'Belum diisi' ? 'entry' : 'audit')}><ArrowRight size={15} /></button></td></tr>)}</tbody></table></div></section>
      <div className="quarter-callout"><div className="quarter-icon"><CalendarDays size={18} /></div><div><strong>Rekap triwulan III siap disusun</strong><span>Data Juli–September ditampilkan per bulan; input langsung tersimpan ke rekap.</span></div><button type="button" onClick={() => onNavigate('reports')}>Buka rekap <ArrowRight size={14} /></button></div>
    </div>
  )
}

export default DashboardPage